---
title: "Solucionario tarea 1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Cargar paquetes
```{r, echo=T, message=FALSE, warning=FALSE}
library(tidyverse)
```


# Ejercicio 1

```{r}
get_cv <- function(x, na.rm = FALSE) {
  if (na.rm) {
    x <- x[!is.na(x)]
  }  
  
  cv <- sd(x) / mean(x) 
    
  return(cv)  
}

```

# Ejercicio 2

```{r}
build_address <- function(street, number, apartment = NULL) {
  
  new_street <- tolower(street) %>% 
    str_remove_all("avenida") %>% 
    str_remove_all("av.") %>% 
    str_remove_all("av") %>% 
    str_remove_all("calle|pasaje")  %>% 
    str_trim(side = "both")
  
  new_number <- tolower(number) %>% 
    str_extract("[[:digit:]]+")
  
 # Caminos diferenciados para el caso con y sin departamento  
 if (!is.null(apartment)) {
    new_apartment <- tolower(apartment) %>% 
    str_extract("[[:digit:]]+")
    new_apartment <- paste("depto.", new_apartment[[1]])
    
    final_address <- paste(new_street, new_number[[1]])
    final_address <- paste(final_address, new_apartment, sep = ", ")

 } else {
    final_address <- paste(new_street, new_number[[1]])
    
  }
  
  return(final_address)

  
}

```

# Ejercicio 3

```{r, eval=T}

df <- tribble(~calle,              ~numero,      ~depto,
              "calle Hemingway",   "num 345",    "depto. 345",
              "av. Albert Camus",  "número 123", "123",
              "Manuel Rojas",      "234",        "departamento 231",
              "Nicanor Parra",     "678",        NULL
              
              ) 

df %>% 
  rowwise() %>% 
  mutate(direccion = build_address(calle, numero, depto)) 

```
